/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-04-30 10:09:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.new_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1582349879470L));
    _jspx_dependants.put("jar:file:/E:/JAVA_WEB_JSP_SERVLET_JDBC_MYSQL/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/java_web_jsp_servlet_jdbc_mysql/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582293489152L));
    _jspx_dependants.put("jar:file:/E:/JAVA_WEB_JSP_SERVLET_JDBC_MYSQL/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/java_web_jsp_servlet_jdbc_mysql/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1582293489645L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<title>Chart - Admin</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<meta name=\"description\" content=\"overview &amp; stats\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- bootstrap & fontawesome -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/font-awesome/4.5.0/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- page specific plugin styles -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- text fonts -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/fonts.googleapis.com.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace styles -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/ace.min.css\" class=\"ace-main-stylesheet\" id=\"main-ace-style\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/ace-skins.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace settings handler -->\r\n");
      out.write("\t\t<script src=\"assets/js/ace-extra.min.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body class=\"no-skin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<div class=\"main-content-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumbs ace-save-state\" id=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-home home-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/java_web_jsp_servlet_jdbc_mysql/admin-home\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\">Chart</li>\r\n");
      out.write("\t\t\t\t\t\t</ul><!-- /.breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t\tChart\r\n");
      out.write("\t\t\t\t\t\t\t\t<small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-angle-double-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCars &amp; Comments\r\n");
      out.write("\t\t\t\t\t\t\t\t</small>\r\n");
      out.write("\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- /.page-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- PAGE CONTENT BEGINS -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"vspace-12-sm\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"widget-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-header widget-header-flat widget-header-small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-signal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tCars of Sumary\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"piechart-placeholder\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hr hr8 hr-double\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-main -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-body -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-box -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><!-- /.col -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- /.row -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hr hr32 hr-dotted\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hr hr32 hr-dotted\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- PAGE CONTENT ENDS -->\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- /.col -->\r\n");
      out.write("\t\t\t\t\t\t</div><!-- /.row -->\r\n");
      out.write("\t\t\t\t\t</div><!-- /.page-content -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- /.main-content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script src=\"assets/js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif('ontouchstart' in document.documentElement) document.write(\"<script src='assets/js/jquery.mobile.custom.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"assets/js/jquery-ui.custom.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.sparkline.index.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace scripts -->\r\n");
      out.write("\t\t<script src=\"assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/ace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t\t$('.easy-pie-chart.percentage').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';\r\n");
      out.write("\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t$(this).easyPieChart({\r\n");
      out.write("\t\t\t\t\t\tbarColor: barColor,\r\n");
      out.write("\t\t\t\t\t\ttrackColor: trackColor,\r\n");
      out.write("\t\t\t\t\t\tscaleColor: false,\r\n");
      out.write("\t\t\t\t\t\tlineCap: 'butt',\r\n");
      out.write("\t\t\t\t\t\tlineWidth: parseInt(size/10),\r\n");
      out.write("\t\t\t\t\t\tanimate: ace.vars['old_ie'] ? false : 1000,\r\n");
      out.write("\t\t\t\t\t\tsize: size\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.sparkline').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t$(this).sparkline('html',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttagValuesAttribute:'data-values',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype: 'bar',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbarColor: barColor ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchartRangeMin:$(this).data('min') || 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  $.resize.throttleWindow = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var mini = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t  var compact = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t  var midsize = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t  var large = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate[3]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t  var placeholder = $('#piechart-placeholder').css({'width':'90%' , 'min-height':'150px'}); \r\n");
      out.write("\t\t\t  var data = [\r\n");
      out.write("\t\t\t\t{ label: \"Mini Cars\",  data: mini , color: \"#68BC31\"},\r\n");
      out.write("\t\t\t\t{ label: \"Compact Cars\",  data: compact, color: \"#2091CF\"},\r\n");
      out.write("\t\t\t\t{ label: \"Midsize Cars\",  data: midsize, color: \"#AF4E96\"},\r\n");
      out.write("\t\t\t\t{ label: \"Large Cars\",  data: large, color: \"#DA5430\"}\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t\t\t  function drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t \t  $.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tpie: {\r\n");
      out.write("\t\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt:0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight: {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity: 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke: {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor: '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth: 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle: 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend: {\r\n");
      out.write("\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\tposition: position || \"ne\", \r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor: null,\r\n");
      out.write("\t\t\t\t\t\tmargin:[-30,15]\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\t\tclickable: true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t drawPieChart(placeholder, data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t /**\r\n");
      out.write("\t\t\t we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\t so that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t placeholder.data('chart', data);\r\n");
      out.write("\t\t\t placeholder.data('draw', drawPieChart);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //pie chart tooltip example\r\n");
      out.write("\t\t\t  var $tooltip = $(\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\").hide().appendTo('body');\r\n");
      out.write("\t\t\t  var previousPoint = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  placeholder.on('plothover', function (event, pos, item) {\r\n");
      out.write("\t\t\t\tif(item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \" + item.series['percent']+'%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({top:pos.pageY + 10, left:pos.pageX + 10});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(document).one('ajaxloadstart.page', function(e) {\r\n");
      out.write("\t\t\t\t\t$tooltip.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d1 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td1.push([i, Math.sin(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d2 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.5) {\r\n");
      out.write("\t\t\t\t\td2.push([i, Math.cos(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tvar d3 = [];\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < Math.PI * 2; i += 0.2) {\r\n");
      out.write("\t\t\t\t\td3.push([i, Math.tan(i)]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click', function(){\r\n");
      out.write("\t\t\t\t\tif(this.checked) $(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\telse $(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/admin/new/chart.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("APIurl");
      // /views/admin/new/chart.jsp(2,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/api-admin-new");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/admin/new/chart.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("NewURL");
      // /views/admin/new/chart.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/admin-new-list");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
